name: Run Batch Process

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      trigger:
        description: "Manually trigger the batch process"
        required: false

jobs:
  run-batch-process:
    runs-on: ubuntu-latest

    steps:
      # Install and Setup Docker itself
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Get the Batch Process up and running
      - name: Build Batch Image (if necessary)
        if: ${{ needs.build.outputs.image_changed == 'true' }}
        run: docker-compose -f compose.yaml build batch_process

      - name: Run Batch Process Container
        run: docker-compose -f compose.yaml up --no-deps batch_process
        working-directory: .

      - name: Upload Prediction Results
        uses: actions/upload-artifact@v4
        with:
          name: prediction-results
          path: ./batch_process/prediction-results

      - name: Show Docker Logs
        run: docker logs $(docker-compose -f compose.yaml ps -q batch_process)

      - name: Stop Containers (Optional)
        run: docker-compose -f compose.yml down batch_process