name: Run Batch Process

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:
    inputs:
      trigger:
        description: "Manually trigger the batch process"
        required: false

jobs:
  run-batch-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
            docker-compose -f compose.yaml build
        working-directory: .

      - name: Run Batch Process Container
        run: docker-compose -f compose.yaml up --no-deps batch_process
        working-directory: .
